name: glassy_real_navbar
description: Beautiful glassmorphism navigation bar with liquid lens effects, 17+ animations, and drag-to-select.
version: 1.0.3
homepage: https://github.com/salauddinmajumder/glassy_real_navbar
repository: https://github.com/salauddinmajumder/glassy_real_navbar
issue_tracker: https://github.com/salauddinmajumder/glassy_real_navbar/issues

topics:
  - navigation
  - glassmorphism
  - ui
  - animation
  - navbar

# screenshots:
#   - description: 'Glassy navbar with liquid lens effect'
#     path: screenshots/demo.gif

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
